### ISSUE TITLE
Assessment Review: LO 3 Additional Comments

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#103]
# Learning Outcome Criterion: 3
## Criterion:
Identify and apply authorisation, authentication and permission features in a Full-Stack web application solution
## Review:
Currently, only login is implemented, but it is functional. It is ideal to have something for new registration as well.
## Corrective tasks:

- [x] Create groups
- [x] set permissions for groups
- [x] assign users to appropriate groups
- [x] make content available according to role
