### ISSUE TITLE
USER STORY: Optimise User role fuctionality

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#115]
As **site user** I can **access the parts of the app which are relevant to me** so that **I see what I need to see and don't see other parts of the app**.

### Acceptance Criteria
- Acceptance Criteria 1: On login, my role is displayed
- Acceptance Criteria 2: Once logged in, I can access all  parts of the site relevant to my role
- Acceptance Criteria 2: Once logged in, I am unable to access all  parts of the site which are not relevant to my role
- I have functionality CRUD functionality relevant to my role
### Tasks
- [x]  Login determines role
- [x]  role determines site access (by section)
- [x]  role determines data access (by section): only section data displayed
- [x] display reflects role of user : name , section, role

**Comment by mikerae** [comment]
Data is viewable according to membership of a particular section.
Only Rota anagers have access to CRUD functionality.
Currently Orchestral Manager functionality beyond access to the Admin area is not implemented
