### ISSUE TITLE
USER STORY: Login determines role

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#118]
As **site user** I can **access the areas of the site relevant to my role** so that **I can view and edit data relevant to me**.

### Acceptance Criteria
- Acceptance Criteria 1: Log in with specific roles and permissions
- Acceptance Criteria 2: Have my name, role and section displayed clearly
- Acceptance Criteria 2: Access only areas relevant to my role
### Tasks
- [x] set permissions in admin
- [x] design view-url-template flow
- [x] write view-url-template flow for bass section
- [x] write view-url-template flow for vlc, vla, vln2 vln1 sections
- [x] write view-url-template flow for office
