### ISSUE TITLE
USER STORY: Register

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#119]
As **RSNO string player or manager** I can **register ** so that **I can gain access to the site, and my username can be associated with my player profile**.

ref code #138 

### Acceptance Criteria
- If I am a bona-fide site RSNO site user, I can create a username and password
- I can have my username associated with my site profile
- Rota Managers can register existing and new players

### Tasks
- [x] Create players app
- [x] connect registration page
- [x] Display list of unregistered players in rota manager's section
- [x] Add link & functionality to register player
