### ISSUE TITLE
Deploy Initial Project on Heruko

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#12]
As **developer** I can **configure Django and Heroku** so that **I can make an initial deployment**.

### Acceptance Criteria
- Acceptance Criteria 1: Project deploys correctly on Heroku
- Acceptance Criteria 2: Django displays default view correctly on Heroku deployed web site
### Tasks
- [ ] Task 1: Use walkthroughs to correctly configure Django and Heroku
- [ ] Task 2: ensure debug is set to TRUE if initial developer deployment
- [ ] Task 3: document deployment in Readme
