### ISSUE TITLE
USER STORY: Display messages elegantly

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#120]
As **site-user** I can **see app feedback presented elegantly.** so that **I can be reassured  that I am interacting with the app as I want, and that the feedback is easily understandable**.

### Acceptance Criteria
- Acceptance Criteria 1: Messages are clearly displayed after each significant action
- Acceptance Criteria 2: Messages are presented elegantly
### Tasks
- [x] Make sure messages are enabled
- [x] Program message calls where appropriate
- [ ]  Use toasts to display messages
- [ ] Style Toast includes elegantly

**Comment by mikerae** [comment]
Messages are displayed elegantly.
Toasts are not implemented in this version because BootstrapMade uses custom JS which has prevented using jquery effectively within the project deadlines.
