### ISSUE TITLE
USER STORY: Add multiple seating positions at once

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#121]
As **rota manager** I can **add multiple seating positions at once** so that **I do not have to repeatedly save each allocated position when creating a new seating plan**.

### Acceptance Criteria
- Acceptance Criteria 1: Size of section for particular project is displayed 
- Acceptance Criteria 2: All pre-allocated positions are displayed as initial data
- Acceptance Criteria 3: The number of additional forms in formset reflects the number of positions to be filled for that project
- Acceptance Criteria 4: The formset can be submited and forms added in one action
- Acceptance Criteria 4: The newly created seating positions are displayed when submit is returend
### Tasks
- [ ] Task 1: Create default section size in section model
- [ ] Task 2: Create custom section size in section/project seating plan model
- [ ] Task 3: Form: create ModelFormset
- [ ] Task 3: View:  create ModelFormfactory
