### ISSUE TITLE
Assessment Review: LO1 Summary

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#126]
# Learning Outcome Criterion: 1
## Meets Criterion?: N
ref: #123 #124 #125 #127 #128  #129 #130 #131 #132 #133 #141 #148
## Criterion:
Use an Agile methodology to plan and design a Full-Stack Web application using an MVC framework and related contemporary technologies
## Review:
This is an ambitious project which shows good levels of ability with custom data model creation and integration in a relational format. Additionally the Python code indicates good levels of custom logic integration. Unfortunately currently many actions within the application lead to server errors. These include attempting to access any project as an admin user, and for rota managers attempting to add players to a project, toggling between draft and published, or attempting to edit a player's position. As such much of the core functionality is not fully robust. In addition there is some scope for UX improvement. Upon signing in to the application the player is met with an empty project page. Consider displaying some element of a welcome screen. There is some minor horizontal scroll present on the login screen. HTML on the main application once signed in fails validation with a number of issues
## Corrective tasks:

- [x] Create Issues for each of the following:
    - [x] Identify & fix server issues re: "attempting to access any project as an admin user" #127
    - [x] Identify & fix server issues re: "rota managers attempting to add players to a project #129 , toggling between draft and published #128, or attempting to edit a player's position",  #130
     - [x] UX Improvement: " Upon signing in to the application the player is met with an empty project page" #131 
    - [x] UX Improvement: "Consider displaying some element of a welcome screen" #132 
    - [x] UX Improvement: "There is some minor horizontal scroll present on the login screen." #133 
    - [x] Validate HTML #124
