### ISSUE TITLE
USER STORY: Admin and Office can view full orch rotas

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#156]
As **Admin or Office** I can **view rotas for each section for each project** so that **I can know which players are allocated to each project**.
ref: #28 #159 
### Acceptance Criteria
- Office Manager can view published rotas for each section of a particular project
- Draft rotas display draft rota status and no detail for Office Managers
- Admin can view and edit  all rotas for each section of a particular project (is member of Rota Manager Group).
- Draft rotas display draft rota status and no detail for Admin
### Tasks
- [x] Assign Admin to groups: Office, Rota Manager
- [x] Assign Orch manager to group: Office
- [x] For staff: All sections viewable for each project, via Programs  dropdown  menu in sidebar
- [x] Orch Manager cannot access admin
- [x] Section dropdown only available for Office
- [x] Rotas are editable by admin but not by Orchestra Manager

**Comment by mikerae** [comment]
For the first version, all sections are displayed for each project.
If time allows,a javascript will show all sections for the selected project.

**Comment by mikerae** [comment]
At the moment, the Admin Edit/Toggle/delete functionality does not work. see
