### ISSUE TITLE
USER STORY: Change Password

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#166]
As **user** I can **change my password** so that **I can keep acces to my account secure after I have been registerd to the app**.

### Acceptance Criteria
- Acceptance Criteria 1: User can change assigned password
- Acceptance Criteria 2: User can add Email
- Acceptance Criteria 3: User is sent verification email
### Tasks
- [x] Add 'Change password' link to user accounts dropdown
- [x] Add 'Add Email' link to user accounts dropdown
- [x] Test Change password & add to readme
- [x] Test Add Email & add to readme
- [x] Enable email server
- [x] Test Email verification sent
- [x] validate html

**Comment by mikerae** [comment]
Various html validation issues were addressed, mainly in base.html, but some in the allauth templates.
All allauth templates passed validation after corrections were made.
