### ISSUE TITLE
USER STORY: Staff View Only Published Rotas

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#28]
As **Rota-Manager** I can **publish rotas to office staff and section members online and in email/pdf** so **that all parties are accurately informed of rota information and can easily access it in one place.**

ref: #156 #159

### Acceptance Criteria
- Acceptance Criteria 1: All roles  can see if a rota is published or not
- Only display rota detail if a rota is published
### Tasks
- [x] Task 1: Published/Draft field on seating plan
- [x] Task 2: Display published seating plan
- [x] Task 3: Do not display draft/ not created seating plan: show message instead
