### ISSUE TITLE
USER STORY: Log in with Correct Privileges

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#36]
As **Rota-Manager** I can **log into the site with Rota-Manager privileges** so that **I can access the areas and functionality of the site appropriate to my role.**
As  **Project-Assessor** I can **log-in as generic roles**  so that **I can interact with, and asses,  the site from the perspective of all role types.**
As  **superUser** I can log in as SuperUser** so that **I can access and edit all areas for development and deployment purposes.**
As an  **anonymous user** I can **see a top level page which directs me to an RSNO contact, but not gain access to any further parts of the site** so that **the privacy of site is maintained.**
As **office-orchestral-manager** I can **log into the site with office-orchestral-manager privileges** so that **I can access the areas and functionality of the site appropriate to my role.**
As **office-time-off-manager** I can **log into the site with office-time-off-manager privileges** so that **I can access the areas and functionality of the site appropriate to my role.**
As **office-fixer** I can **log into the site with office-fixer privileges** so that **I can access the areas and functionality of the site appropriate to my role.**
As **section-member** I can **log into the site with section-member privileges** so that **I can access the areas and functionality of the site appropriate to my role.**

### Acceptance Criteria
- Acceptance Criteria 1: Django Groups are allocated appropriately to each user and group
- Acceptance Criteria 2: The landing page is a log - in 
- 
### Tasks
- [x] Task 1: Set up groups and permissions
- [x] Task 2: Allocate groups to users
- [x] Task 3: Allow only authenticated users to log in with appropriate privelages/permissions
