### ISSUE TITLE
USER STORY: Import Project Data

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#84]
As  **superUser** I can import RSNO Schedule and Natural Free Day data from csv’s provided for this project by the RSNO** so that **I can populate the project database to simulate live data.**

### Acceptance Criteria
- Acceptance Criteria 1: Designated fields from program csv is viewable in the program models in the admin section by super user
- Acceptance Criteria 2: Designated fields from Natural Free Day csv is viewable in the player model in the  admin section by super user

### Tasks
- [x] Task 1: Research process....
- [x] Task 2: Create simulated remote RSNO db googledrive worksheet
- [x] Task 3: write import utility
- [x] Task 3: import csv data to remote RSNO
- [x] Task 4: Write import script
- [ ] Task 5 document process in ReadmMe
