### ISSUE TITLE
Create Database Schema

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#91]
As **developer** I can **refer to the project Schema** so that **I can design  database models**
### Tasks
- [x] Create Full Database Schema for String Rota project
- [x] Export Schema image
- [x] Add Schema image to project
- [x] Update Readme
