### ISSUE TITLE
USER STORY: Create Super User

### ISSUE THREAD

**Issue by mikerae** [mikerae/string-rota#92]
As **superUser** I can **I can log in as SuperUser** so that **I can access and edit all areas for development and deployment purposes.**

### Acceptance Criteria
- Acceptance Criteria 1: Access Admin area of Django deployed site
- Acceptance Criteria 2: Non-SuperUser cannot access Admin area
### Tasks
- [x] Task 1: Create SuperUser
- [x] Task 2: Log in as Superuser
- [x] Task 3: Test non-access for non-super-user
